export const GET_GROCERIES_SUCCESS = 'GET_GROCERIES_SUCCESS'
export const ADD_GROCERY_SUCCESS = 'ADD_GROCERY_SUCCESS'
export const DELETE_GROCERY_SUCCESS = 'DELETE_GROCERY_SUCCESS'
export const BUY_GROCERY_SUCCESS = 'BUY_GROCERY_SUCCESS'